layout_spectrum: 0.2851064
name: 'Smokeshisha '
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
typography_spectrum: 0.4404255
color:
  brandStrength: 0.4085106
  lightness: 0.4907251
  saturation: 1
  rhythmicContrast: 0.3212766
  brandColors:
    - '#F4F1E3'
    - '#BEAC0F'
    - '#150C27'
    - '#772830'
    - '#E1D76E'
