layout_spectrum: 0
name: 'Smokeshisha '
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.7765958
color:
  brandStrength: 1
  lightness: 0.3617021
  saturation: 0.2170213
  rhythmicContrast: 1
  brandColors:
    - '#F4F1E3'
    - '#BEAC0F'
    - '#150C27'
    - '#772830'
    - '#E1D76E'
