layout_spectrum: 0.5170213
typography_spectrum: 0.7765958
color:
  lightness: 0.3617021
  brandStrength: 1
  saturation: 0.9191489
  rhythmicContrast: 0.312766
  brandColors:
    - '#020105'
    - '#5B6665'
    - '#CEA380'
    - '#FF7FFF'
    - '#FDFFFF'
name: 'Smokeshisha '
