layout_spectrum: 0.5659574
name: 'Smokeshisha '
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  saturation: 0.9191489
  brandColors:
    - '#020105'
    - '#5B6665'
    - '#CEA380'
    - '#FF7FFF'
    - '#FDFFFF'
  lightness: 0.3617021
  rhythmicContrast: 0.312766
typography_spectrum: 0.7765958
